### ISSUE TITLE
03 シェルスクリプトがいいのか直接コマンド叩いたほうがいいのか？

### ISSUE THREAD

**Issue by kzfm** [cbi-society/cheminfo_tutorial_20241028#21]
gypsum実行例でスクリプトを書き換えるようになっていますが、conda activateで仮想環境を変更して直接コマンドを叩いてもいいように思いました。

pen先生にお任せします。

**Comment by iwatobipen** [comment]
ご指摘のとおり環境を変更して実行がリーズナブルなのですがハンズオンで切り替えること自体がリスクになりそうな気がしたのでノートブック側からコールする方法で行きたいと思います。
