### ISSUE TITLE
maize.tomlにいろいろ設定を書かなければいけない意義がわからない

### ISSUE THREAD

**Issue by kzfm** [cbi-society/cheminfo_tutorial_20241028#6]
pythonが仮想環境毎に設定しなければいけないのは、ハンズオンの最初に書き換える必要があるしconda infoでenvsを見ながら適当なパスの設定をするのは時間がかかりそう。

そして、最初にハンズオンの全体像を示さないといきなりつまずいて置いてけぼりをくらうひとがおおいのではないか？

**Comment by iwatobipen** [comment]
確かにわかりにくいのですが、REINVENTやGypsumなど外部環境をMaizeの環境から利用するという柔軟性を持たせるために必要なのだと理解しています。
説明せず設定して下さいのみだと、たしかにわかりにくいので、最初に説明を入れるようにします。

**Comment by kzfm** [comment]
02を00にして説明を丁寧に加えればよいかと思います。
